model:
  params:
    n_estimators: [100, 200, 300]
    max_depth: [3, 10]
    learning_rate: [0.01, 0.3]
    feature_fraction: [0.5, 1.0]
    bagging_fraction: [0.5, 1.0]
    num_leaves: [20, 100]
    lambda_l1: [0.0, 1.0]
    lambda_l2: [0.0, 1.0]

    subsample_freq: [1]